import { ReportTemplate, ReportSection, DataRequirement, ChartConfig } from './index';

export const advisoryReportsTemplate: ReportTemplate = {
  id: 'advisory-reports-package',
  name: 'Advisory Reports Package',
  description: 'Comprehensive advisory reporting package including business health scorecard, benchmark analysis, trend analysis, and strategic recommendations',
  category: 'advisory',
  type: 'business_scorecard',
  version: '1.0.0',
  layout: {
    pageSize: 'Letter',
    orientation: 'portrait',
    margins: {
      top: 72,
      right: 54,
      bottom: 72,
      left: 54,
    },
    header: {
      enabled: true,
      height: 50,
      content: 'Business Advisory Report - {{client.businessName}} - {{reportDate}}',
    },
    footer: {
      enabled: true,
      height: 30,
      content: 'Page {{pageNumber}} of {{totalPages}} | Strategic Advisory Services',
    },
    coverPage: {
      enabled: true,
      template: 'advisory-cover',
    },
    tableOfContents: {
      enabled: true,
      depth: 2,
    },
  },
  sections: [
    // Executive Dashboard
    {
      id: 'executive-dashboard',
      name: 'Executive Dashboard',
      type: 'chart',
      required: true,
      order: 1,
      config: {
        layout: 'dashboard',
        kpiCards: [
          'revenue_growth',
          'profit_margin',
          'cash_position',
          'debt_ratio',
          'efficiency_score',
          'growth_trajectory',
        ],
        alertThresholds: true,
        trendIndicators: true,
      },
      dataSource: 'business_metrics',
    },
    // Business Health Scorecard
    {
      id: 'business-health-scorecard',
      name: 'Business Health Scorecard',
      type: 'table',
      required: true,
      order: 2,
      config: {
        categories: [
          'financial_strength',
          'operational_efficiency',
          'market_position',
          'growth_potential',
          'risk_management',
          'organizational_capability',
        ],
        scoringSystem: '1-10',
        includeWeights: true,
        showBenchmarks: true,
        includeActionItems: true,
        colorCoding: true,
      },
      dataSource: 'health_scorecard',
    },
    // Industry Benchmark Analysis
    {
      id: 'benchmark-analysis',
      name: 'Industry Benchmark Analysis',
      type: 'chart',
      required: true,
      order: 3,
      config: {
        metrics: [
          'gross_margin',
          'operating_margin',
          'current_ratio',
          'debt_equity_ratio',
          'inventory_turnover',
          'accounts_receivable_days',
          'revenue_per_employee',
        ],
        benchmarkSources: ['industry_average', 'top_quartile', 'top_decile'],
        showGaps: true,
        includeCommentary: true,
      },
      dataSource: 'benchmark_data',
    },
    // Financial Trend Analysis
    {
      id: 'financial-trends',
      name: 'Financial Trend Analysis',
      type: 'chart',
      required: true,
      order: 4,
      config: {
        timeframe: '36_months',
        metrics: [
          'revenue',
          'gross_profit',
          'operating_profit',
          'net_profit',
          'cash_flow',
          'working_capital',
        ],
        trendLines: true,
        seasonalAdjustment: true,
        forecastingPeriod: 12,
        includeConfidenceIntervals: true,
      },
      dataSource: 'financial_trends',
    },
    // Operational Metrics Analysis
    {
      id: 'operational-metrics',
      name: 'Operational Performance Metrics',
      type: 'chart',
      required: true,
      order: 5,
      config: {
        categories: [
          'productivity',
          'quality',
          'customer_satisfaction',
          'employee_engagement',
          'process_efficiency',
        ],
        includeTargets: true,
        showTrends: true,
        periodicComparison: true,
        includeCorrelations: true,
      },
      dataSource: 'operational_data',
    },
    // Key Performance Indicators Deep Dive
    {
      id: 'kpi-deep-dive',
      name: 'Key Performance Indicators Deep Dive',
      type: 'chart',
      required: true,
      order: 6,
      config: {
        primaryKPIs: [
          'customer_acquisition_cost',
          'customer_lifetime_value',
          'monthly_recurring_revenue',
          'churn_rate',
          'gross_margin_per_customer',
          'sales_cycle_length',
        ],
        drillDownCapability: true,
        cohortAnalysis: true,
        segmentAnalysis: true,
        showDrivers: true,
      },
      dataSource: 'kpi_detailed',
    },
    // Cash Flow Analysis & Projections
    {
      id: 'cash-flow-analysis',
      name: 'Cash Flow Analysis & Projections',
      type: 'chart',
      required: true,
      order: 7,
      config: {
        analysisType: 'comprehensive',
        timeframes: ['historical_12', 'projection_12'],
        scenarios: ['conservative', 'realistic', 'optimistic'],
        includeSeasonality: true,
        showSensitivity: true,
        includeStressTest: true,
      },
      dataSource: 'cash_flow_analysis',
    },
    // Profitability Analysis
    {
      id: 'profitability-analysis',
      name: 'Profitability Analysis by Segment',
      type: 'chart',
      required: true,
      order: 8,
      config: {
        segments: ['product_line', 'customer_segment', 'geographic_region', 'sales_channel'],
        analysisDepth: 'detailed',
        includeMarginWaterfall: true,
        showCostDrivers: true,
        includeOptimizationOpportunities: true,
      },
      dataSource: 'profitability_data',
    },
    // Risk Assessment Matrix
    {
      id: 'risk-assessment',
      name: 'Business Risk Assessment',
      type: 'table',
      required: true,
      order: 9,
      config: {
        riskCategories: [
          'financial',
          'operational',
          'strategic',
          'compliance',
          'technology',
          'market',
          'reputation',
        ],
        riskMatrix: true,
        impactAssessment: true,
        probabilityAssessment: true,
        mitigationStrategies: true,
        prioritization: true,
      },
      dataSource: 'risk_assessment',
    },
    // Strategic Recommendations
    {
      id: 'strategic-recommendations',
      name: 'Strategic Recommendations',
      type: 'narrative',
      required: true,
      order: 10,
      config: {
        categories: [
          'growth_opportunities',
          'operational_improvements',
          'cost_optimization',
          'cash_management',
          'risk_mitigation',
          'technology_investments',
        ],
        prioritization: 'impact_effort_matrix',
        timelineMapping: true,
        resourceRequirements: true,
        expectedOutcomes: true,
        aiEnhanced: true,
      },
      dataSource: 'strategic_analysis',
    },
    // Action Plan & Implementation
    {
      id: 'action-plan',
      name: 'Action Plan & Implementation Roadmap',
      type: 'table',
      required: true,
      order: 11,
      config: {
        timeframes: ['30_days', '90_days', '6_months', '12_months'],
        includeOwnership: true,
        includeResources: true,
        includeMilestones: true,
        includeMetrics: true,
        trackingMechanism: true,
      },
      dataSource: 'action_plan',
    },
    // Market Intelligence
    {
      id: 'market-intelligence',
      name: 'Market Intelligence & Competitive Landscape',
      type: 'narrative',
      required: false,
      order: 12,
      config: {
        includeMarketTrends: true,
        competitiveAnalysis: true,
        threatAssessment: true,
        opportunityMapping: true,
        customerInsights: true,
        aiGenerated: true,
      },
      dataSource: 'market_data',
    },
  ],
  dataRequirements: [
    {
      source: 'quickbooks',
      entity: 'financial_statements',
      fields: ['revenue', 'expenses', 'assets', 'liabilities', 'cash_flow'],
      filters: { period: 'last_36_months' },
      required: true,
    },
    {
      source: 'database',
      entity: 'business_metrics',
      fields: ['metric_name', 'value', 'target', 'benchmark', 'trend'],
      required: true,
    },
    {
      source: 'database',
      entity: 'industry_benchmarks',
      fields: ['industry', 'metric', 'percentile_25', 'median', 'percentile_75'],
      required: true,
    },
    {
      source: 'calculated',
      entity: 'performance_ratios',
      fields: ['ratio_name', 'value', 'trend', 'industry_comparison'],
      required: true,
    },
    {
      source: 'manual',
      entity: 'strategic_goals',
      fields: ['goal', 'target', 'timeline', 'priority'],
      required: false,
    },
  ],
  chartConfigs: [
    {
      id: 'business-health-radar',
      type: 'gauge',
      title: 'Business Health Radar',
      dataSource: 'health_scorecard',
      options: {
        type: 'radar',
        categories: 6,
        maxScore: 10,
        showBenchmark: true,
      },
    },
    {
      id: 'revenue-trend-analysis',
      type: 'line',
      title: 'Revenue Trend Analysis (36 Months)',
      dataSource: 'financial_trends',
      xAxis: 'month',
      yAxis: 'revenue',
      series: ['actual', 'trend', 'forecast'],
      colors: ['#2563eb', '#059669', '#dc2626'],
    },
    {
      id: 'profitability-waterfall',
      type: 'bar',
      title: 'Profitability Waterfall Analysis',
      dataSource: 'profitability_data',
      options: {
        type: 'waterfall',
        showConnectors: true,
        positiveColor: '#22c55e',
        negativeColor: '#ef4444',
      },
    },
    {
      id: 'cash-flow-projection',
      type: 'area',
      title: 'Cash Flow Projection (12 Months)',
      dataSource: 'cash_flow_analysis',
      xAxis: 'month',
      yAxis: 'cash_balance',
      series: ['conservative', 'realistic', 'optimistic'],
      colors: ['#f59e0b', '#3b82f6', '#10b981'],
    },
    {
      id: 'industry-benchmarks',
      type: 'bar',
      title: 'Industry Benchmark Comparison',
      dataSource: 'benchmark_data',
      xAxis: 'metric',
      yAxis: 'value',
      series: ['company', 'industry_average', 'top_quartile'],
      colors: ['#2563eb', '#64748b', '#059669'],
    },
    {
      id: 'risk-matrix',
      type: 'heatmap',
      title: 'Risk Assessment Matrix',
      dataSource: 'risk_assessment',
      options: {
        xAxis: 'probability',
        yAxis: 'impact',
        colorScale: ['#22c55e', '#f59e0b', '#ef4444'],
        bubbleSize: 'risk_score',
      },
    },
  ],
  brandingOptions: {
    logo: {
      enabled: true,
      position: 'header',
      size: 'medium',
    },
    colors: {
      primary: '#1e40af',
      secondary: '#64748b',
      accent: '#059669',
      text: '#1f2937',
    },
    fonts: {
      heading: 'Inter',
      body: 'Inter',
      size: 'medium',
    },
    layout: {
      margins: 54,
      spacing: 16,
      columnCount: 1,
    },
  },
};