import { ReportTemplate, ReportSection, DataRequirement } from './index';

export const taxPreparationTemplate: ReportTemplate = {
  id: 'tax-preparation-package',
  name: 'Tax Preparation Package',
  description: 'Comprehensive tax preparation package including document checklist, tax organizer, prior year comparison, and estimated payments',
  category: 'tax_preparation',
  type: 'tax_organizer',
  version: '1.0.0',
  layout: {
    pageSize: 'Letter',
    orientation: 'portrait',
    margins: {
      top: 72,
      right: 54,
      bottom: 72,
      left: 54,
    },
    header: {
      enabled: true,
      height: 50,
      content: 'Tax Preparation Package - {{client.businessName}} - Tax Year {{taxYear}}',
    },
    footer: {
      enabled: true,
      height: 30,
      content: 'Page {{pageNumber}} of {{totalPages}} | Confidential Tax Information',
    },
    coverPage: {
      enabled: true,
      template: 'tax-cover',
    },
    tableOfContents: {
      enabled: true,
      depth: 2,
    },
  },
  sections: [
    // Tax Preparation Overview
    {
      id: 'tax-overview',
      name: 'Tax Preparation Overview',
      type: 'narrative',
      required: true,
      order: 1,
      config: {
        includeDeadlines: true,
        includeStrategy: true,
        includeChanges: true,
        taxYear: '{{taxYear}}',
      },
      dataSource: 'tax_overview',
    },
    // Document Checklist
    {
      id: 'document-checklist',
      name: 'Required Documents Checklist',
      type: 'table',
      required: true,
      order: 2,
      config: {
        categories: [
          'income_documents',
          'deduction_documents',
          'business_records',
          'investment_records',
          'personal_information',
        ],
        showStatus: true,
        showDeadlines: true,
        includeNotes: true,
      },
      dataSource: 'document_checklist',
    },
    // Tax Organizer - Business Information
    {
      id: 'business-information',
      name: 'Business Information',
      type: 'table',
      required: true,
      order: 3,
      config: {
        sections: [
          'basic_info',
          'ownership_structure',
          'accounting_method',
          'business_activity',
          'elections',
        ],
        allowEditing: true,
        validateFields: true,
      },
      dataSource: 'business_info',
    },
    // Income Summary
    {
      id: 'income-summary',
      name: 'Income Summary',
      type: 'financial_statement',
      required: true,
      order: 4,
      config: {
        statementType: 'income_summary',
        includeComparisons: true,
        comparisonPeriods: ['prior_year'],
        showVariance: true,
        categories: [
          'gross_receipts',
          'cost_of_goods_sold',
          'gross_profit',
          'other_income',
        ],
      },
      dataSource: 'income_data',
    },
    // Deductions Summary
    {
      id: 'deductions-summary',
      name: 'Business Deductions Summary',
      type: 'financial_statement',
      required: true,
      order: 5,
      config: {
        statementType: 'deductions_summary',
        includeComparisons: true,
        comparisonPeriods: ['prior_year'],
        showVariance: true,
        categories: [
          'advertising',
          'car_truck_expenses',
          'commissions_fees',
          'contract_labor',
          'employee_benefits',
          'insurance',
          'legal_professional',
          'office_expenses',
          'rent_lease',
          'repairs_maintenance',
          'supplies',
          'taxes_licenses',
          'travel_meals',
          'utilities',
          'other_expenses',
        ],
        validateAmounts: true,
      },
      dataSource: 'deductions_data',
    },
    // Asset & Depreciation Schedule
    {
      id: 'asset-depreciation',
      name: 'Asset & Depreciation Schedule',
      type: 'table',
      required: true,
      order: 6,
      config: {
        includeAssets: ['equipment', 'vehicles', 'furniture', 'software', 'improvements'],
        showDepreciation: true,
        show179Election: true,
        showBonusDepreciation: true,
        calculateRemaining: true,
      },
      dataSource: 'asset_data',
    },
    // Prior Year Comparison
    {
      id: 'prior-year-comparison',
      name: 'Prior Year Tax Comparison',
      type: 'table',
      required: true,
      order: 7,
      config: {
        compareFields: [
          'gross_income',
          'total_deductions',
          'taxable_income',
          'federal_tax',
          'state_tax',
          'self_employment_tax',
          'estimated_payments',
          'refund_owed',
        ],
        showVariance: true,
        showPercentageChange: true,
        highlightSignificantChanges: true,
      },
      dataSource: 'prior_year_data',
    },
    // Estimated Tax Payments
    {
      id: 'estimated-payments',
      name: 'Estimated Tax Payments Schedule',
      type: 'table',
      required: true,
      order: 8,
      config: {
        nextYear: '{{nextTaxYear}}',
        quarters: ['Q1', 'Q2', 'Q3', 'Q4'],
        includeDueDates: true,
        showCalculations: true,
        includeSafeHarbor: true,
        includeReminders: true,
      },
      dataSource: 'estimated_payments',
    },
    // Tax Planning Opportunities
    {
      id: 'tax-planning',
      name: 'Tax Planning Opportunities',
      type: 'narrative',
      required: false,
      order: 9,
      config: {
        categories: [
          'retirement_planning',
          'business_structure',
          'timing_strategies',
          'deduction_optimization',
          'credit_opportunities',
        ],
        aiGenerated: true,
        includeActionItems: true,
        includeTimelines: true,
      },
      dataSource: 'tax_planning',
    },
    // Supporting Schedules
    {
      id: 'supporting-schedules',
      name: 'Supporting Tax Schedules',
      type: 'table',
      required: false,
      order: 10,
      config: {
        schedules: [
          'schedule_c',
          'schedule_se',
          'form_4562',
          'form_8829',
          'state_schedules',
        ],
        showCalculations: true,
        validateTotals: true,
      },
      dataSource: 'tax_schedules',
    },
    // Engagement Letter & Terms
    {
      id: 'engagement-terms',
      name: 'Engagement Letter & Terms',
      type: 'text',
      required: true,
      order: 11,
      config: {
        includeScope: true,
        includeResponsibilities: true,
        includeFees: true,
        includeDeadlines: true,
        requireSignature: true,
      },
      dataSource: 'engagement_letter',
    },
  ],
  dataRequirements: [
    {
      source: 'quickbooks',
      entity: 'profit_loss',
      fields: ['account', 'amount', 'tax_category'],
      filters: { year: '{{taxYear}}' },
      required: true,
    },
    {
      source: 'quickbooks',
      entity: 'balance_sheet',
      fields: ['account', 'balance', 'asset_type'],
      filters: { date: 'year_end' },
      required: true,
    },
    {
      source: 'database',
      entity: 'tax_documents',
      fields: ['document_type', 'status', 'received_date', 'notes'],
      required: true,
    },
    {
      source: 'database',
      entity: 'prior_year_returns',
      fields: ['line_items', 'amounts', 'schedules'],
      required: true,
    },
    {
      source: 'manual',
      entity: 'business_elections',
      fields: ['election_type', 'status', 'effective_date'],
      required: false,
    },
  ],
  chartConfigs: [
    {
      id: 'income-comparison',
      type: 'bar',
      title: 'Income Comparison - Current vs Prior Year',
      dataSource: 'income_data',
      xAxis: 'income_category',
      yAxis: 'amount',
      series: ['current_year', 'prior_year'],
      colors: ['#2563eb', '#94a3b8'],
    },
    {
      id: 'deduction-breakdown',
      type: 'pie',
      title: 'Business Deductions Breakdown',
      dataSource: 'deductions_data',
      series: ['category'],
      colors: ['#dc2626', '#ea580c', '#d97706', '#65a30d', '#059669', '#0891b2'],
    },
    {
      id: 'tax-liability-trend',
      type: 'line',
      title: 'Tax Liability Trend (5 Years)',
      dataSource: 'tax_history',
      xAxis: 'year',
      yAxis: 'total_tax',
      series: ['federal', 'state', 'self_employment'],
      colors: ['#1e40af', '#dc2626', '#059669'],
    },
  ],
  brandingOptions: {
    logo: {
      enabled: true,
      position: 'header',
      size: 'medium',
    },
    colors: {
      primary: '#1e40af',
      secondary: '#64748b',
      accent: '#dc2626',
      text: '#1f2937',
    },
    fonts: {
      heading: 'Inter',
      body: 'Inter',
      size: 'medium',
    },
    layout: {
      margins: 54,
      spacing: 12,
      columnCount: 1,
    },
  },
};