export const clientsData = {
  'taxpro': [
    {
      businessName: 'TechFlow Solutions Inc',
      legalName: 'TechFlow Solutions Incorporated',
      taxId: '77-1234567',
      quickbooksId: 'qb_techflow_001',
      primaryContactEmail: 'sarah.cfo@techflow.com',
      primaryContactName: 'Sarah Chang',
      primaryContactPhone: '(415) 555-0123',
      businessAddress: '123 Innovation Drive, San Francisco, CA 94105',
      mailingAddress: '123 Innovation Drive, San Francisco, CA 94105',
      businessType: 'Corporation',
      industry: 'Technology',
      website: 'https://techflow.com',
      status: 'active',
      riskLevel: 'medium',
      annualRevenue: 2450000.00,
      employeeCount: 18,
      yearEstablished: 2018,
      servicePackage: 'full_service',
      billingFrequency: 'monthly'
    },
    {
      businessName: 'Golden Gate Medical Group',
      legalName: 'Golden Gate Medical Group, P.C.',
      taxId: '94-7654321',
      quickbooksId: 'qb_ggmedical_002',
      primaryContactEmail: 'admin@goldengatemed.com',
      primaryContactName: 'Dr. Michael Rodriguez',
      primaryContactPhone: '(415) 555-0789',
      businessAddress: '456 Medical Plaza, San Francisco, CA 94102',
      mailingAddress: '456 Medical Plaza, San Francisco, CA 94102',
      businessType: 'Professional Corporation',
      industry: 'Healthcare',
      website: 'https://goldengatemed.com',
      status: 'active',
      riskLevel: 'low',
      annualRevenue: 1875000.00,
      employeeCount: 12,
      yearEstablished: 2010,
      servicePackage: 'cfo_services',
      billingFrequency: 'monthly'
    },
    {
      businessName: 'Bay Area Real Estate Holdings LLC',
      legalName: 'Bay Area Real Estate Holdings LLC',
      taxId: '46-9876543',
      quickbooksId: 'qb_bare_003',
      primaryContactEmail: 'finance@bareh.com',
      primaryContactName: 'Jennifer Thompson',
      primaryContactPhone: '(415) 555-0456',
      businessAddress: '789 Property Lane, San Mateo, CA 94401',
      mailingAddress: 'PO Box 12345, San Mateo, CA 94401',
      businessType: 'LLC',
      industry: 'Real Estate',
      website: 'https://bareh.com',
      status: 'active',
      riskLevel: 'high',
      annualRevenue: 8750000.00,
      employeeCount: 8,
      yearEstablished: 2015,
      servicePackage: 'full_service',
      billingFrequency: 'quarterly'
    },
    {
      businessName: 'Pacific Import Export Co',
      legalName: 'Pacific Import Export Company',
      taxId: '32-5432109',
      quickbooksId: 'qb_pacific_004',
      primaryContactEmail: 'accounting@pacificimport.com',
      primaryContactName: 'David Kim',
      primaryContactPhone: '(510) 555-0234',
      businessAddress: '101 Harbor View, Oakland, CA 94607',
      mailingAddress: '101 Harbor View, Oakland, CA 94607',
      businessType: 'Corporation',
      industry: 'Import/Export',
      website: 'https://pacificimport.com',
      status: 'active',
      riskLevel: 'high',
      annualRevenue: 12500000.00,
      employeeCount: 25,
      yearEstablished: 2005,
      servicePackage: 'full_service',
      billingFrequency: 'monthly'
    },
    {
      businessName: 'Green Valley Organic Farms',
      legalName: 'Green Valley Organic Farms LLC',
      taxId: '68-1357924',
      quickbooksId: 'qb_greenvalley_005',
      primaryContactEmail: 'owner@greenvalleyorganic.com',
      primaryContactName: 'Maria Gonzalez',
      primaryContactPhone: '(707) 555-0567',
      businessAddress: '2500 Farm Road, Napa, CA 94558',
      mailingAddress: '2500 Farm Road, Napa, CA 94558',
      businessType: 'LLC',
      industry: 'Agriculture',
      website: 'https://greenvalleyorganic.com',
      status: 'active',
      riskLevel: 'medium',
      annualRevenue: 850000.00,
      employeeCount: 15,
      yearEstablished: 2012,
      servicePackage: 'tax_and_bookkeeping',
      billingFrequency: 'monthly'
    }
  ],
  'qbadvisory': [
    {
      businessName: 'Austin Coffee Collective',
      legalName: 'Austin Coffee Collective LLC',
      taxId: '75-2468135',
      quickbooksId: 'qb_austincoffee_006',
      primaryContactEmail: 'owner@austincoffee.com',
      primaryContactName: 'Jake Martinez',
      primaryContactPhone: '(512) 555-0890',
      businessAddress: '345 South Lamar, Austin, TX 78704',
      mailingAddress: '345 South Lamar, Austin, TX 78704',
      businessType: 'LLC',
      industry: 'Food & Beverage',
      website: 'https://austincoffee.com',
      status: 'active',
      riskLevel: 'medium',
      annualRevenue: 485000.00,
      employeeCount: 8,
      yearEstablished: 2019,
      servicePackage: 'bookkeeping_plus',
      billingFrequency: 'monthly'
    },
    {
      businessName: 'Lone Star Consulting Group',
      legalName: 'Lone Star Consulting Group PLLC',
      taxId: '20-8642097',
      quickbooksId: 'qb_lonestar_007',
      primaryContactEmail: 'admin@lonestaronsulting.com',
      primaryContactName: 'Rebecca Johnson',
      primaryContactPhone: '(512) 555-0345',
      businessAddress: '567 Congress Ave, Austin, TX 78701',
      mailingAddress: '567 Congress Ave, Austin, TX 78701',
      businessType: 'PLLC',
      industry: 'Professional Services',
      website: 'https://lonestarconsulting.com',
      status: 'active',
      riskLevel: 'low',
      annualRevenue: 725000.00,
      employeeCount: 6,
      yearEstablished: 2017,
      servicePackage: 'advisory_plus',
      billingFrequency: 'monthly'
    },
    {
      businessName: 'Hill Country Construction',
      legalName: 'Hill Country Construction LLC',
      taxId: '55-9753186',
      quickbooksId: 'qb_hillcountry_008',
      primaryContactEmail: 'finance@hillcountryconstruction.com',
      primaryContactName: 'Robert Davis',
      primaryContactPhone: '(512) 555-0678',
      businessAddress: '890 Industrial Blvd, Round Rock, TX 78664',
      mailingAddress: 'PO Box 67890, Round Rock, TX 78664',
      businessType: 'LLC',
      industry: 'Construction',
      website: 'https://hillcountryconstruction.com',
      status: 'active',
      riskLevel: 'medium',
      annualRevenue: 1250000.00,
      employeeCount: 22,
      yearEstablished: 2014,
      servicePackage: 'full_service',
      billingFrequency: 'monthly'
    },
    {
      businessName: 'Music City Retail',
      legalName: 'Music City Retail Inc',
      taxId: '73-4561289',
      quickbooksId: 'qb_musiccity_009',
      primaryContactEmail: 'accounting@musiccityretail.com',
      primaryContactName: 'Amanda Wilson',
      primaryContactPhone: '(512) 555-0912',
      businessAddress: '234 Music Lane, Austin, TX 78702',
      mailingAddress: '234 Music Lane, Austin, TX 78702',
      businessType: 'Corporation',
      industry: 'Retail',
      website: 'https://musiccityretail.com',
      status: 'active',
      riskLevel: 'medium',
      annualRevenue: 950000.00,
      employeeCount: 14,
      yearEstablished: 2016,
      servicePackage: 'bookkeeping_plus',
      billingFrequency: 'monthly'
    }
  ],
  'smithjones': [
    {
      businessName: 'Portland Family Dentistry',
      legalName: 'Portland Family Dentistry PC',
      taxId: '93-7412580',
      quickbooksId: 'qb_portlanddental_010',
      primaryContactEmail: 'office@portlandfamilydentistry.com',
      primaryContactName: 'Dr. Lisa Chen',
      primaryContactPhone: '(503) 555-0123',
      businessAddress: '123 Dental Drive, Portland, OR 97201',
      mailingAddress: '123 Dental Drive, Portland, OR 97201',
      businessType: 'Professional Corporation',
      industry: 'Healthcare',
      website: 'https://portlandfamilydentistry.com',
      status: 'active',
      riskLevel: 'low',
      annualRevenue: 650000.00,
      employeeCount: 5,
      yearEstablished: 2008,
      servicePackage: 'tax_only',
      billingFrequency: 'annual'
    },
    {
      businessName: 'Mountain View Landscaping',
      legalName: 'Mountain View Landscaping LLC',
      taxId: '85-9638520',
      quickbooksId: 'qb_mountainview_011',
      primaryContactEmail: 'info@mountainviewlandscaping.com',
      primaryContactName: 'Carlos Rodriguez',
      primaryContactPhone: '(503) 555-0456',
      businessAddress: '456 Garden Way, Beaverton, OR 97005',
      mailingAddress: 'PO Box 456, Beaverton, OR 97005',
      businessType: 'LLC',
      industry: 'Landscaping',
      website: 'https://mountainviewlandscaping.com',
      status: 'active',
      riskLevel: 'medium',
      annualRevenue: 285000.00,
      employeeCount: 8,
      yearEstablished: 2018,
      servicePackage: 'tax_and_bookkeeping',
      billingFrequency: 'quarterly'
    },
    {
      businessName: 'Pacific Northwest Consulting',
      legalName: 'Patricia Johnson, CPA',
      taxId: '91-1472583',
      primaryContactEmail: 'patricia@pnwconsulting.com',
      primaryContactName: 'Patricia Johnson',
      primaryContactPhone: '(503) 555-0789',
      businessAddress: '789 Business Center Dr, Lake Oswego, OR 97034',
      mailingAddress: '789 Business Center Dr, Lake Oswego, OR 97034',
      businessType: 'Sole Proprietorship',
      industry: 'Professional Services',
      website: 'https://pnwconsulting.com',
      status: 'active',
      riskLevel: 'low',
      annualRevenue: 125000.00,
      employeeCount: 1,
      yearEstablished: 2020,
      servicePackage: 'tax_only',
      billingFrequency: 'annual'
    }
  ]
};

export const servicePackages = {
  'tax_only': {
    name: 'Tax Preparation Only',
    description: 'Annual tax return preparation and filing',
    services: ['tax_preparation', 'tax_filing', 'basic_tax_planning'],
    monthlyFee: 0,
    hourlyRate: 150
  },
  'tax_and_bookkeeping': {
    name: 'Tax & Bookkeeping',
    description: 'Monthly bookkeeping and annual tax preparation',
    services: ['monthly_bookkeeping', 'financial_statements', 'tax_preparation', 'tax_filing'],
    monthlyFee: 500,
    hourlyRate: 125
  },
  'bookkeeping_plus': {
    name: 'Bookkeeping Plus',
    description: 'Enhanced bookkeeping with management reporting',
    services: ['monthly_bookkeeping', 'financial_statements', 'management_reports', 'cash_flow_analysis', 'tax_preparation'],
    monthlyFee: 750,
    hourlyRate: 125
  },
  'advisory_plus': {
    name: 'Advisory Plus',
    description: 'Strategic business advisory with bookkeeping',
    services: ['monthly_bookkeeping', 'financial_statements', 'business_advisory', 'strategic_planning', 'tax_preparation'],
    monthlyFee: 1200,
    hourlyRate: 175
  },
  'full_service': {
    name: 'Full Service',
    description: 'Comprehensive accounting and advisory services',
    services: ['monthly_bookkeeping', 'financial_statements', 'management_reports', 'business_advisory', 'tax_preparation', 'audit_support', 'compliance'],
    monthlyFee: 2000,
    hourlyRate: 200
  },
  'cfo_services': {
    name: 'CFO Services',
    description: 'Outsourced CFO and comprehensive financial management',
    services: ['monthly_bookkeeping', 'financial_statements', 'management_reports', 'business_advisory', 'strategic_planning', 'cash_flow_management', 'board_reporting', 'tax_preparation', 'audit_support'],
    monthlyFee: 3500,
    hourlyRate: 250
  }
};

export const industries = [
  'Technology',
  'Healthcare',
  'Real Estate',
  'Import/Export',
  'Agriculture',
  'Food & Beverage',
  'Professional Services',
  'Construction',
  'Retail',
  'Landscaping',
  'Manufacturing',
  'Education',
  'Non-Profit',
  'Financial Services',
  'Transportation',
  'Entertainment',
  'Hospitality',
  'Energy',
  'Legal Services',
  'Marketing/Advertising'
];