source "https://rubygems.org"

gem "jekyll", "~> 4.3"
gem "just-the-docs", "~> 0.6.2"
gem "webrick", "~> 1.8"

group :jekyll_plugins do
  gem "jekyll-remote-theme", "~> 0.4.3"
  gem "jekyll-sitemap", "~> 1.4"
  gem "jekyll-feed", "~> 0.17"
  gem "jekyll-seo-tag", "~> 2.8"
end
